### ISSUE TITLE
Option to set the number of visible native tabs per pane

### ISSUE THREAD

**Issue by N3C2L** [oxdc/obsidian-vertical-tabs#1]
Hello and thank you for the plugin!
Would it be possible to add a toggle command for making the native tabs visible? 
It would be useful to make them visible with a command, as this would allow users to move these tabs between tab groups in the native tabs UI. Once a user is done moving or renaming them, we could reduce the tab count again to one tab per pane for the readibility with the toggle command. Another idea might be to also be able to set the number of tabs to display before or after the current tab per pane.
Thanks!

**Comment by oxdc** [comment]
Thanks for your feedback!

The naive tabs are visible. You can drag and drop them to move tabs between groups. By default, only the active tab in each group is visible. You may click the button at the top-left corner to show all open tabs, which is the default layout of Obsidian.

<img width="1013" alt="pin" src="https://github.com/user-attachments/assets/a933c8dd-e9dd-47fc-b6ce-a234fd996909">

> Another idea might be to also be able to set the number of tabs to display before or after the current tab per pane.

Great idea! This would be implemented in the next release.

**Comment by N3C2L** [comment]
Wonderful, thank you for this toggle; I must have overlooked this button at first. 😄
Thank you also for implementing my idea in the next release.

**Comment by N3C2L** [comment]
Please excuse me for not being a developer, but perhaps there are other possibilities that could enable implementation from your perspective:
An option to always move the currently clicked tab to the beginning of the tab group (Most Recently Used - MRU). This would have the advantage that no tabs before or after would need to be considered. The current tab would always be displayed on the far left in the current pane, along with only the number of additional tabs you have set, for example, 3 or 4 more tabs that were displayed in the current pane after the first clicked tab. This would be similar to the tab switcher known from operating systems, which also uses Alt+Tab in MRU order.

**Comment by oxdc** [comment]
Great idea! The Obsidian API, however, doesn't offer explicit and direct ways for manipulating tabs. I'll look into it and hope can find a solution.

**Comment by N3C2L** [comment]
I remembered a plugin (pane relief) that offers a command for putting a tab as a first tab:

![image](https://github.com/user-attachments/assets/f6db1d1e-7ee8-48c9-82b3-1cd10362ae76)

You can find the project with the code here:

https://github.com/pjeby/pane-relief

I hope this helps!

It's installable also via the Obsidian community store inside Obsidian.

**Comment by N3C2L** [comment]
Maybe it would be ok if these two things should be separated?
So, feature 1: list active tab in MRU order, and 2. (for later) set the number of tabs per pane.
I don't really need the number of tabs per pane if MRU could be activated and then I can set a fixed tab width like:

/* fixed tab width */
.workspace .mod-root .workspace-tab-header {
    min-width: 250px;
    max-width: 250px;
}
.workspace-tab-header {
    display: block;
}

The tabs can be displayed with a fixed width, regardless of how much text the tab title contains. This way, it would be possible to always display a fixed width of tabs; the rest of the tabs would simply be hidden on my screen (That would be a good alternative to displaying a fixed number of tabs per pane). This would always display enough text from any tabs in any pane.

**Comment by oxdc** [comment]
> feature 1: list active tab in MRU order

This is now available in v0.3.0 🎉
