### ISSUE TITLE
Icon misalignment in zen mode

### ISSUE THREAD

**Issue by plant-eye** [oxdc/obsidian-vertical-tabs#15]
Collapsing the left sidebar causes its icon to misalign, but it only happens in zen mode. 
(Also, it would be very useful to have a zen hotkey option!)

![image](https://github.com/user-attachments/assets/e30f375e-7ed0-4f52-ab03-d021f11bbc95)

**Comment by oxdc** [comment]
Thank you for reporting. I have noticed this issue. I am going to try a better way of managing the sidebar collapse buttons ASAP

**Comment by oxdc** [comment]
This problem should be corrected in the latest version (v.0.6.10). Please update and ‼️ **reopen Obsidian** ‼️.

If you encounter similar issues, please reopen an issue.
