### ISSUE TITLE
Update adds two left and right side bar buttons

### ISSUE THREAD

**Issue by aikruger** [oxdc/obsidian-vertical-tabs#16]
The latest update adds an extra left and right side bar button to the top navigation of obsidian
![image_435](https://github.com/user-attachments/assets/a42653ca-24f6-49db-9260-5c52d558cc93)

**Comment by oxdc** [comment]
It appears to be some CSS issue. I'll look into it. Thank you for reporting.

**Comment by oxdc** [comment]
This problem should be corrected in the latest version (v.0.6.10). Please update and ‼️ **reopen Obsidian** ‼️.

If you encounter similar issues, please reopen an issue.
