### ISSUE TITLE
Hotkey for Zen mode

### ISSUE THREAD

**Issue by freyart** [oxdc/obsidian-vertical-tabs#17]
Love the plugin,

It would be nice to have the possibility to switch zen mode with the press of a hotkey.

Thanks!

**Comment by oxdc** [comment]
Hi! This is already in my plan! I'm working on the setting view, which would bring all kinds of customizations and tweaks together.

**Comment by oxdc** [comment]
Hi! I added a new command to toggle Zen Mode. Customizable hotkey can be set in the "Settings" > "Hotkeys". 🎉
