### ISSUE TITLE
Right mouse button would accidently close the tab

### ISSUE THREAD

**Issue by Moyf** [oxdc/obsidian-vertical-tabs#18]
![41fb6e0a-8b93-4c4b-8649-eff345bd107e](https://github.com/user-attachments/assets/9e414670-3e85-4edf-97ee-308be970b683)

The yellow point stands for Left click, and the red stands for right click.
As you can see, now when I right-click in the tab, it would close the tab.

Plugin version: 0.6.2
Platform: Windows
Obsidian version: 1.7.0

**Comment by Moyf** [comment]
Nevermind.. After a while it recovered by itself.
Really doubt I have something continuously conflicting lol.

Next time I'll try in Sandbox firstly, sorry : /

**Comment by oxdc** [comment]
There are several ways to close the tab right now:

1. Left click the close icon;
2. Right click the tab and choose "close" in the menu;
3. Double click the tab;
4. Middle click the tab;
5. Left click the tab with Alt/Option key held.

Unfortunately, I cannot reproduce this bug. Could you please provide a detailed steps? By the way, if there is some issue with your hardware, especially for wireless and Bluetooth mice, you may accidentally triggered a double click.

**Comment by kdqiu** [comment]
Thanks for your wonderful plugin, it helps me a lot.
I also have this question. I tried in Sandbox, and it's the same. I checked the console, but there's nothing.
Plugin version: 0.6.5
Platform: Windows
Obsidian version: 1.6.7

**Comment by oxdc** [comment]
@kdqiu @Moyf Could you please provide a detailed steps for reproducing? It seems that this issue only happens on Windows. Since I don't have a Windows PC at hand, it would be hard for me to debug without further information.

**Comment by oxdc** [comment]
This should be fixed now. Please upgrade to the latest version (v0.6.6) ASAP. Thank you for your feedback.

If you encounter this again, please reopen this issue.
