### ISSUE TITLE
Pin icon seems not synced.

### ISSUE THREAD

**Issue by Moyf** [oxdc/obsidian-vertical-tabs#19]
![image](https://github.com/user-attachments/assets/24d0add7-4cfd-4e77-9f6d-b096b24b180f)

*This time I tried in Sandbox vault 😸*

![ea609e1b-a189-42a7-aa87-167eee3c0883](https://github.com/user-attachments/assets/8c5e5989-426b-4cc9-a242-bdd0102e3dff)

**Comment by Moyf** [comment]
Oh.. this time the #18 issue appeared again, in sandbox vault 🤔

**Comment by oxdc** [comment]
Thanks. The problem is: If you pin/unpin a tab with Obsidian's native menu, *Vertical Tabs* would not be notified so that the UI does not reflect the change. I'll try to find a way to make this work.
