### ISSUE TITLE
Bug: Second click needed to activate a tab

### ISSUE THREAD

**Issue by N3C2L** [oxdc/obsidian-vertical-tabs#2]
I found a bug:

1. open a sandbox vault with the command palette
2. install brat plugin and vertical tabs only
3. open a new tab and create a new markdown file
4. click inside this new markdown file and write a random word
5. click on another tab inside the vertical tabs sidebar
6. Result is that 2 clicks are needed to switch to the desired tab

**Comment by oxdc** [comment]
Thank you for your feedback. Could you please replace the `main.js` file in the plugin folder `.obsidian/plugins/obsidian-vertical-tabs` with the modified version in the following archive? I made a small change, it works fine on my Mac now.

[main.js.zip](https://github.com/user-attachments/files/16374491/main.js.zip)

If it did work for you as well, I will publish a new release.

**Comment by N3C2L** [comment]
It's working good with your changes, thank you! Tested on Windows OS.
