### ISSUE TITLE
Two tap to change a tab on mobile (iOS and iPadOS)

### ISSUE THREAD

**Issue by Azmoinal** [oxdc/obsidian-vertical-tabs#24]
As for the title, I noticed that on my iPad if I use an external keyboard (magic keyboard) I can click on a row on the left sidebar and a click is enough to change immediately the active tab. 

However on the same iPad, and on my iPhone, if I tried to tab on a row I have to tap twice to switch the active tab. 

The first tap seems to select the right row and the second one to effectively activate it. 

Is it an expected behavior?

**Comment by oxdc** [comment]
This bug has been fixed in the latest version. Thank you. If you experience this again, please reopen this issue.
