### ISSUE TITLE
Click Tab in Hidden Group Should be Displayed

### ISSUE THREAD

**Issue by fornewfork** [oxdc/obsidian-vertical-tabs#25]
Currently, when a tab within a hidden group is clicked, the group remains hidden and the tab is not displayed.

When a tab within a hidden group is clicked, the group should be set as visible and the clicked tab should be displayed.

Thank you for your nice work!

**Comment by oxdc** [comment]
Thank you!

> Currently, when a tab within a hidden group is clicked, the group remains hidden and the tab is not displayed.

This is, in fact, intended behavior. I admit that it is unintuitive and could cause confusion. May I ask which of the following solutions you think is the best option?

1. When a group is hidden, display only its name and hide all the tabs within the group. When the user search a tab (implementing), matched tabs of a hidden group will be displayed, but greyed out.

eg.

Before:

- Group 1:
  - Tab 1
  - Tab 2
- Group 2:
  - Tab 3

After:

- Group 1 (hidden)
- Group 2:
  - Tab 3

Search for the keyword "2":

- Group 1 (hidden)
  - Tab **2**
- Group **2**

2. (As described in your request) Show the hidden group and the tabs within. When a tab is clicked, automatically unhide the group and open the tab.

**Comment by fornewfork** [comment]
I think we could keep both solutions, since they work fine for different cases.

- For case of **few goups with many tabs in each group**, the **search solution** is better.

eg.

Group 1:
Tab 1
Tab 2
...
Tab 10

Group 2:
Tab 11
...
Tab 20

- For case of **many goups with few tabs in each group**, the **click solution** is better.

eg.

Group 1:
Tab 1
Tab 2
Tab 3
Group 2:
Tab 4
Tab 5
Tab 6
...
Group 5:
Tab 13
Tab 14
Tab 15

**Comment by oxdc** [comment]
> When a tab within a hidden group is clicked, the group should be set as visible and the clicked tab should be displayed.

The original feature has been implemented. I'll release this shortly. More refinement will come after refactoring.
