### ISSUE TITLE
Window controls (minimise to tray and windowed display) don't work when hiding grouped tabs

### ISSUE THREAD

**Issue by plant-eye** [oxdc/obsidian-vertical-tabs#28]
Not sure if those are the right terms for it since english isn't my first language, but I noticed this issue coming up whenever I hide grouped tabs, works normally if all tabs are visible.

**Comment by oxdc** [comment]
Could you please provide a screenshot or video recording? BTW, may I ask if you are able to share the debug info? You may follow [the official instructions](https://help.obsidian.md/Help+and+support#Collect+debug+information).

**Comment by plant-eye** [comment]
I noticed the same exact issue with the "close" button, right after I screenrecorded

[obsidian vertical tabs minimise+window bug.zip](https://github.com/user-attachments/files/17001742/obsidian.vertical.tabs.minimise%2Bwindow.bug.zip)

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.5.3
	Operating system: Windows 10 Pro 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Vertical Tabs v0.6.8

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by oxdc** [comment]
Thank you for providing detailed information. I'll look into it shortly.

**Comment by oxdc** [comment]
This problem should be corrected in the latest version (v.0.6.10). Please update and ‼️ **reopen Obsidian** ‼️.

If you encounter similar issues, please reopen an issue.
