### ISSUE TITLE
Conflict with plugins (Tab Switcher and Recent Tab Switcher)

### ISSUE THREAD

**Issue by kdqiu** [oxdc/obsidian-vertical-tabs#29]
Thanks for the nice plugin🙏. 
I'm used to using a shortcut/hotkey that switches to the previously active tab. Tab Switcher and Recent Tab Switcher can achive that. However, they conflict with vertical tabs. When "show active tab" is active, I cannot switch.
Can you check that? Thanks🙏

**Comment by kdqiu** [comment]
> Thanks for the nice plugin🙏. I'm used to using a shortcut/hotkey that switches to the previously active tab. Tab Switcher and Recent Tab Switcher can achive that. However, they conflict with vertical tabs. When "show active tab" is active, I cannot switch. Can you check that? Thanks🙏

Tab Switcher can not use in obsidian1.6.7

**Comment by oxdc** [comment]
Tab Switcher works fine on my computer. Could you please try to reproduce this in Sandbox Vault? BTW, *Vertical Tabs* is mean to replace all existence tab management plugins, thus no compatibility will be ensured. If you want a missing feature from another plugin, please open a FR.

**Comment by oxdc** [comment]
Tab Switcher works fine on my computer. Could you please try to reproduce this in Sandbox Vault?

BTW, the goal of *Vertical Tabs* is to replace all existing tab management plugins, thus no compatibility will be ensured. If you want a missing feature from another plugin, please open a FR.

**Comment by kdqiu** [comment]
> Tab Switcher works fine on my computer. Could you please try to reproduce this in Sandbox Vault?
> 
> BTW, the goal of _Vertical Tabs_ is to replace all existing tab management plugins, thus no compatibility will be ensured. If you want a missing feature from another plugin, please open a FR.

Thanks for your reply. I just try Tab switch again, it works. I'll close this issue. Thanks again.
