### ISSUE TITLE
Moving plugin tab into split editor should not create separate group

### ISSUE THREAD

**Issue by lguenth** [oxdc/obsidian-vertical-tabs#35]
Hi oxdc! 
I just stumbled upon your plugin 5 minutes ago through the OMG Discord server and immediately managed to mess something up which might be circumvented from your side...

When you drag the plugin's own tab from the sidebar into the general editor area and split the editor into two panes/groups, the new tab group is shown as empty. If you then, stupidly, also hide the group, you cannot access the plugin tab anymore until you disable and re-enable the plugin OR go into zen mode. :sweat_smile: 

[obsidian-verttabs-bug.webm](https://github.com/user-attachments/assets/dd727e12-832d-4542-93a5-904c74f1c0b7)

The video hopefully explains that better than I can manage in words. Obviously, this is more a user error than a bug but I have some suggestions regarding this problem that I wanted to share. Feel free to ignore.

The main issue to think about is how you handle the plugin's own tab. It doesn't appear in the sidebar groups and therefore is also "invisible" in the list when dropped in the editor. It might make sense *not* to leave it out. Similarly, I feel like you should add a check to the "hide group" and perhaps also the "zen mode" feature which excludes the plugin's own tab. 

Thanks for making this!

**Comment by oxdc** [comment]
> The main issue to think about is how you handle the plugin's own tab.

Yes, this is tricky! I have noticed this problem before making this plugin public. I'm still figuring out the best UX solution. BTW, thank you for reporting this. I'll keep this issue open for anyone who might accidentally hide *Vertical Tabs*.

**Comment by oxdc** [comment]
A simple fix: *Vertical Tabs* now resides in sidebars only. Please update to the latest version. Thank you.
