### ISSUE TITLE
Can't drag and drop

### ISSUE THREAD

**Issue by Lotus49b** [oxdc/obsidian-vertical-tabs#36]
I'm not sure if this worked for me before (?) but it seems I can't drag and drop between groups (see attached).

I'm not seeing any errors on the console either. Any ideas?

![image](https://github.com/user-attachments/assets/26d1c75c-911f-4bb0-80ff-7b7ba2e92fe7)

**Comment by oxdc** [comment]
Thank you for reporting the problem.

Since v0.6.9: Manual tab sorting will be disabled when automatic sorting is enabled.

I'm working on refining the drag-and-drop experience. Will be fixed soon!

**Comment by Lotus49b** [comment]
Ah! I see it works if I disable Auto Sorting. Thanks!

**Comment by oxdc** [comment]
> this worked for me before

I reverted it to its previous config (maybe temporarily?). Drag&drop should work in all cases.
