### ISSUE TITLE
Option to change default behaviour in the tab view, automatic collapse

### ISSUE THREAD

**Issue by elvarb** [oxdc/obsidian-vertical-tabs#37]
When viewing grouped tab list in Vertical Tabs they by default show all expanded to get a better view of individual tabs that are open. This list can become very long and becomes unmanageable fast.

Having the option to change the default behaviour over all, or even better per tab group. If the group should be by default, expanded or collapsed.

---

Background

I am using a CSS snippet that helps managing multiple files being open in the same window/group, really helpful. Allows for multiple tab rows, see here for details, https://gist.github.com/digitalsignalperson/56fe3cbcf41707cb97362234cb07ccb0

Being able to see the full name of all the tabs that are open is not a requirement for me but what I do instead with Vertical Tabs is to have tab groups for specific types of content. For example I have a Tab Group specifically for periodic notes, like daily notes and then I often end up with a tab group per project. The option of hiding specific tab group is a gamechanger for working with Obsidian and switching between projects.

**Comment by oxdc** [comment]
I added a button to collapse or expand all groups except the sidebars. Per-group auto collapsing is not included right now, since it might complicate the UX. Feel free to comment if this does not match your needs! Thank you.
