### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by winged-voices** [oxdc/obsidian-vertical-tabs#40]
I suspect this is a new update issue -- I just went to install this and it's giving me a "Plugin ID mismatch" error on the Obsidian installer. Help?

**Comment by oxdc** [comment]
Duplicated: #31

*Vertical Tabs* does not support old versions of Obsidian. Installation is, therefore, disabled to prevent inconsistent performance. Please **download the latest installer of Obsidian** to update.
