### ISSUE TITLE
FR: Switch to toggle other groups to "not visible" when selecting a file in a group

### ISSUE THREAD

**Issue by Lotus49b** [oxdc/obsidian-vertical-tabs#43]
Hi me again! 

I'm using this plugin heavily now to help focus on my workflows. I find it better for some reason than Workspaces - maybe it's because it shows Workspaces (the tab groups) and also gives quick access/visibility of tabs).

It would be great if an option existed (there's still room for another icon in the little toolbar above VT! - see 1 below😁) to "auto-invisible" the inactive groups when clicking a file.

Use case:
I'm now working on "German study notes" - the other folders are not visible in the workspace (see 3)
I'm done with that, and now I click on "Outline of video script" (see 2) - the other tab folders will become "not visible" automatically and I don't have to manually change the visibility
![image](https://github.com/user-attachments/assets/0249c4a5-1db2-4bcb-967a-66b14c3aa557)

Thanks again

**Comment by oxdc** [comment]
> to "auto-invisible" the inactive groups when clicking a file
> the other tab folders will become "not visible".

Thank you. Do you mean "to automatically fold inactive groups, like the one named "Gov" in your screenshots"? If you want to hide them, you don't have to manually click the "eye" icon; Zen Mode will automatically hide all the tabs and groups except the one you are working on.

**Comment by Lotus49b** [comment]
Thanks. 
TBH (bit embarrassed about this) I never really looked at Zen mode, thinking it was a "total workspace clearing" thing the way Obsidian does it.
I just tried it and it does the job, although it does remove all the group tabs on the tab bar except for the active tab. But I'm going to work with that for now and see if it makes for an easy workflow.

**Comment by oxdc** [comment]
> although it does remove all the group tabs on the tab bar except for the active tab

This behavior is intended to let you focus on one note at a time, even when there are too many of them. All other tabs are still accessible in *Vertical Tabs*.

I'll close this issue now. If you have further questions or related suggestions, feel free to reopen it! Thank you.
