### ISSUE TITLE
Too easy to select a tab on mobile (iOS/iPadOS)

### ISSUE THREAD

**Issue by Azmoinal** [oxdc/obsidian-vertical-tabs#47]
I noticed that, if there are too much tabs opened (I know that is not a good way to proceed I hope you could forgive me) and you have to scroll the list, basically if the point on which you tap to scroll is the name of a tab, it will be selected after the scrolling ends.

To avoid it I started to tap on the name of a group when I would scroll to search if a tab is open (for instance) but I don't want to change the current tab.

This behaviour is evident on my iPhone and makes difficult to manage a long list of tabs on it, while on my iPad is not so noticeable but it is still here.

**Comment by oxdc** [comment]
Thank you for reporting this bug! I'll try to fix it ASAP.

**Comment by oxdc** [comment]
Hi! Scrolling should work on mobile now ~ Please update to v0.10.0. If you encounter any problem, please reopen this issue. Thank you.

**Comment by Azmoinal** [comment]
I can confirm that it works fine with latest update. Thanks a lot for the fix!
