### ISSUE TITLE
Groups - Auto-close and font style change

### ISSUE THREAD

**Issue by Lotus49b** [oxdc/obsidian-vertical-tabs#48]
Hi there! This plugin continues to make work easier!

I think I mentioned this before, but maybe you can keep these ideas in mind while you're working on more great features.

1. I'm using Zen mode as you suggested in order to avoid manually closing the current group when opening notes in another group (I don't want multiple windows open). An "auto-close group on switching notes in another group" option would be nice (but not essential).
2. There's almost no visual difference between folders and notes in the tree, except for a small indent. Maybe use a bold font for the group title to make it stand out a bit more? (but please don't create a solid background behind it as that will detract from the active note highlighting)

Thanks for the good work, much appreciated.

**Comment by oxdc** [comment]
> An "auto-close group on switching notes in another group" option would be nice

Forgive me. I still didn't get what you mean by "auto-closing groups". Could you please record a demo video or provide a screenshot of it? Thank you.

> There's almost no visual difference between folders and notes in the tree, except for a small indent. Maybe use a bold font for the group title to make it stand out a bit more?

Unfortunately, this design is adopted by Obsidian and *Vertical Tabs* should not deviate too much from it in order to provide a consistent UI to the users. The indent should be clearly marked by a vertical indicator.

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/384ce443-d3ac-4c96-b03e-b5350fcc9174">

If the vertical indicator is not visible, I'm afraid that this could be an issue of your theme.

**Comment by Lotus49b** [comment]
Hi! 
So here I am working on the German study note. The folder 1 is visible, and 2 is invisible because I don't want multiple windows open, but seeing multiple notes on the tab bar is good (although only one note in this folder).
![image](https://github.com/user-attachments/assets/a5eef5b5-7140-4d42-ac16-f0ddcdff732d)

Action 1. Now I open a note from folder 2, and I have 2 windows open at once. 
![image](https://github.com/user-attachments/assets/fb0a8a2b-9190-490d-8096-035658dda2a9)

Action 2. I will now click the eye on folder 1 to make it invisible, so I will have only one window open.
![image](https://github.com/user-attachments/assets/8555cc2e-ce0e-4af6-9584-044eefcfcdbe)

It would speed up the workflow if Action 2 was automatic. But as I said earlier, this is not an essential feature, just a quality of life thing. You are doing very useful things on the plugin and this shouldn't fill up your to do list. As we discussed before, using Zen mode accomplishes this to some extent.

Also, thanks for the bold font CSS snippet. That does the job perfectly (as you can see from the above screenshots).

**Comment by oxdc** [comment]
> using Zen mode accomplishes this *to some extent*

May I ask if there is anything missing or unsatisfactory by using the Zen Mode? Especially comparing to your proposal? I want to understand more about your needs. Thank you.

**Comment by Lotus49b** [comment]
Zen mode is fine, but sometimes it's necessary to see all the tabs in the tab bar when the left sidebar is minimised, eg. when working with wide notes (tables etc.)

**Comment by oxdc** [comment]
> It would speed up the workflow if Action 2 was automatic.

I'm afraid this feature would break Obsidian's design and interrupt other users' workflow. Automatically hiding inactive groups will make it difficult to setup a side-by-side view.

> Zen mode does work when you get used to it, the trick is in shifting your habitual focus from the tab bar to the side.

This is *Vertical Tabs* all about!

> but sometimes it's necessary to see all the tabs in the tab bar when the left sidebar is minimised

Got it, I'll add an option for this feature when the setting page come out. Thank you for your feedback!

**Comment by oxdc** [comment]
I have made some modifications to the Zen Mode. Now, you may achieve your proposal by the following steps:

1. Enable *Zen mode*;
2. Disable *Show active tabs only*.

After these two steps, *Vertical Tabs* will hide inactive groups but show all your horizontal tabs within the active group. You may hide the sidebar (and *Vertical Tabs* view) without losing the sight and control of other tabs.

I'll close this issue right now. The feature above will be available a few days later, after I fully tested some changes. Please update when it comes out. If you run into some problems related to this feature, please reopen this issue.
