### ISSUE TITLE
Mobile compatibility: No ability to close tab

### ISSUE THREAD

**Issue by hdsateyate** [oxdc/obsidian-vertical-tabs#52]
On version 0.10.0 it is not possible to close tabs on mobile. I updated just now, I'm not sure what version I was on before I updated.

Previously the icon was not visible (due to requiring hover) but the functionality was there if you pressed in the right area which was working for me.

Now it appears the button does not exist on mobile at all, making it visible in CSS does nothing.

Please bring back the close tab functionality and make it visible at all times on mobile.

Thanks!

**Comment by oxdc** [comment]
Thank you for your feedback.

> Previously the icon was not visible (due to requiring hover) but the functionality was there if you pressed

Yes. This button is designed for desktop, not tuned for mobile.

> making it visible in CSS does nothing.

I'm sorry but CSS won't bring it back since I have completely removed this button from mobile platforms. It simply does not exist.

> On version 0.10.0 it is not possible to close tabs on mobile.

You may long press the tab to open the context menu and close the tab or other tabs from there.

> Please bring back the close tab functionality and make it visible at all times on mobile.

I'm working on a better design, please wait patiently. As I said, previously the icon is suitable for desktops but for mobile. I found it is too easy to accidentally close a tab, which might cause trouble for many users.

**Comment by hdsateyate** [comment]
Did you get many complaints in relation to people closing tabs accidentally?

An alternative flow to address that outcome would be an undo close toast that pops up for a few seconds as in Chrome for example.

**Comment by hdsateyate** [comment]
Another alternative would be swipe to close but I expect that is significantly more work than bringing back the old functionality and implementing an undo.

In fact the undo would be useful in both instances.

**Comment by oxdc** [comment]
Thank you! I'll consider your suggestions.

**Comment by oxdc** [comment]
Hi @hdsateyate , you may try closing a tab by double tapping it on mobile. I'm not sure if this is the right design. Might be removed in the future. Please feel free to share your thoughts!

**Comment by hdsateyate** [comment]
> Hi @hdsateyate , you may try closing a tab by double tapping it on mobile. I'm not sure if this is the right design. Might be removed in the future. Please feel free to share your thoughts!

I don't mind it. Happy to live with that, thanks.

However, now that you have brought my attention to it, it would be preferable to me for the sidebar not to auto-close after a double tap close action, what do you think?

Quite often when I am in the sidebar closing tabs it is because I want to close multiple tabs quickly having to reopen the sidebar each time provides a little more friction.

Many thanks,

**Comment by oxdc** [comment]
> having to reopen the sidebar each time

Yeah, that is why I think this is not a good design. I will try to pin the sidebar or something else like swipe menu, not sure if these could work. Thank you for sharing your thoughts!

**Comment by oxdc** [comment]
In the next version, a new feature called "Tab Editing" will reveal the close buttons. Please note that you need to disable "Tab Editing" before navigating.

<img width="300" alt="image" src="https://github.com/user-attachments/assets/df3243ce-588b-4195-b876-387d82910755" />

**Comment by hdsateyate** [comment]
Thanks! I'm excited to test it out!

**Comment by oxdc** [comment]
Hi @hdsateyate ! The newly designed features are now publicly available.
