### ISSUE TITLE
[iPad] Context menu not tappable

### ISSUE THREAD

**Issue by Azmoinal** [oxdc/obsidian-vertical-tabs#56]
I've found an issue with the context menu on iPad.

To reproduce it, I triggers the context menu long tapping on a tab name in *Vertical Tabs* after that I try to tap on, for instance, *Browse History*, *Zoom* or *More options* but no one is selectable while the, let me say, *standard* entries as the ones between *Bookmark* and *Open in new window*.

The specific vertical tabs entries works fine on desktop and my iPhone. 

I cannot test right now but I suspect that they work also on iPad if I connect a mouse or the Magic Keyboard. As I said it is just an idea.

**Comment by oxdc** [comment]
Hi! Thank you for posting this issue.

I tried a couple of times on my iPhone and everything works fine. I cannot reproduce it. Unfortunately I don't have an iPad to test 🤣.

May I ask which version of Obsidian you are using? And could you please try to reproduce it in a new vault without enabling other plugins and snippets? This info will help me debugging. Thank you.

**Comment by Azmoinal** [comment]
Hi, I will try later to reproduce in a new vault since I've a lot of plugins installed and some of them adds items into the context menu.

In any case, I can confirm that it is visible only on my iPad while on my iOS device it works fine. 

As soon as I will be at home, I'll play with it.

**Comment by Azmoinal** [comment]
Ok. I reproduced the issue with a fresh vault without any plugin than Vertical tabs and the behavior is the same... Only on iPad (it works fine on MacBook and iPhone).

Moreover, it doesn't work even if I tries to tap the context menu or to click it using the touchpad of the Magic Keyboard.

Just to clarify the part that doesn't work is the one circled in red in the attached ![image](https://github.com/user-attachments/assets/bb45b286-b4ca-4cb5-950c-d8e0f701a822)

The upper part of the context menu is reachable using tap or click.

**Comment by oxdc** [comment]
@Azmoinal Thank you for providing these details. May I ask whether entries like "Forward" "Back" and "Bookmark history" work? You can try these steps:

1. Open a note with links in it.
2. Click one of the link to navigate to another note. This generates a history record for this tab.
3. Now try something like "Back", "Bookmark history" or "Open history in new group" in the menu.

If these entries work fine, this might be an issue with submenus. Thank you a lot for helping me testing!

**Comment by Azmoinal** [comment]
Hi @oxdc, I can confirm your hypothesis.

I created two files and linked them in the empty vault and I can use all entries (e.g. back/forward or "open history in a new group") but the submenus are not working so only the following elements are unavailable:
- Browse history
- Zoom
- More options

**Comment by oxdc** [comment]
Thank you for providing this crucial information! I'll try to figure out the cause.

**Comment by oxdc** [comment]
Hi @Azmoinal ! Since I don't have a device to test, I cannot find the exact cause of this issue. It seems to be [a limitation of Obsidian](https://forum.obsidian.md/t/how-to-show-a-contextual-submenu-in-mobile-obsidian/87532). If I'm correct, there is no submenu on iPad and iOS. Could you please help me confirm this by checking all the native menus? Thank you!

**Comment by Azmoinal** [comment]
I checked the context menus in file explorer, bookmarks, search panes and tapping on tabs and, indeed, it seems that there are not submenus on the iPad interface.

I didn't notice it before your message.

**Comment by oxdc** [comment]
@Azmoinal Thank you so much! I'll redesign the UI on mobile to make these features more accessible.

> The strange thing is that on iOS vertical tabs submenus are working fine.

This is because on iOS, Obsidian uses JS to render the menu; on iPad, however, Obsidian invokes some API to show a native menu.

**Comment by bakebakebakebake** [comment]
> Ok. I reproduced the issue with a fresh vault without any plugin than Vertical tabs and the behavior is the same... Only on iPad (it works fine on MacBook and iPhone).
> 
> Moreover, it doesn't work even if I tries to tap the context menu or to click it using the touchpad of the Magic Keyboard.
> 
> Just to clarify the part that doesn't work is the one circled in red in the attached ![image](https://private-user-images.githubusercontent.com/160850709/383583753-bb45b286-b4ca-4cb5-950c-d8e0f701a822.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNzcxNTMsIm5iZiI6MTczMzM3Njg1MywicGF0aCI6Ii8xNjA4NTA3MDkvMzgzNTgzNzUzLWJiNDViMjg2LWI0Y2EtNGNiNS05NTBjLWQ4ZTBmNzAxYTgyMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMDUzNDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGVmNGQ4OTcxM2E2Y2UwMmIyNGZhYWUxNTNkMTc1MGQ0MTIwZWFjMWYzZTI3NGNlMWY0NDU0MDg5OWU5MDk0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZrtxOgNMdXeB0yt_EeAji_JoD_eb-wgZIr_15z2AGAY)
> 
> The upper part of the context menu is reachable using tap or click.
> 
> Obsidian version is the latest 1.7.5 and the same is for vertical tabs.

Can I ask you an unrelated question? There is a display bug on my iPad, even after updating to the latest version. 

As shown in the image:
![c0f718c0ef81f72c7d2b5e5dac423982](https://github.com/user-attachments/assets/9736a12e-db35-48a7-9ee6-e891ce5be130)

When I press the pin,It looks like the width of the left sidebar is too small. I used the following CSS snippet:

body{
    --mobile-left-sidebar-width: 400pt;
}

However, it doesn't work.

Do you have a solution for this?

**Comment by oxdc** [comment]
Hi @Azmoinal ! In the next release, all functions should be accessible on mobile.

*Expanded menu items*

<img width="500" alt="SCR-20241226-tbhi" src="https://github.com/user-attachments/assets/ceda7a2d-ce5e-408d-8820-72b57c3d20ad" />

*New tab-history browser for mobile*

<img width="500" alt="SCR-20241226-tbls" src="https://github.com/user-attachments/assets/bfdd47d6-031d-4fd5-ad32-868ee0f135ff" />

**Comment by Azmoinal** [comment]
Thanks a lot. It feels native for both Obsidian and iPadOS.

**Comment by oxdc** [comment]
Hi @Azmoinal ! Thank you for reporting the issue and helping me improve Vertical Tabs. The new version is now available.

> P.S. It is out of topic, but could I kindly ask you which is the theme you are using?

It's [Primary for Obsidian](https://github.com/primary-theme/obsidian)!
