### ISSUE TITLE
Save open/closed state for groups

### ISSUE THREAD

**Issue by shef-ski** [oxdc/obsidian-vertical-tabs#65]
Recently, I reported [an issue](https://github.com/oxdc/obsidian-vertical-tabs/issues/44) about the ordering of groups after restarting Obsidian which got resolved very quickly.

I wanted to ask whether it would also be possible to save the open/closed state of groups in addition to their ordering. Currently, all groups open up once I restart obsidian.
Thank you for creating and maintaining this great plugin.

**Comment by oxdc** [comment]
Thank you! I'll try to make this work.
