### ISSUE TITLE
Add a Settings Tab in the Settings UI

### ISSUE THREAD

**Issue by mjmaurer** [oxdc/obsidian-vertical-tabs#68]
Love your plugin, but would be great to configure settings visually. Here's the developer docs on the topic: https://docs.obsidian.md/Plugins/User+interface/Settings

**Comment by oxdc** [comment]
Hi @mjmaurer ! Thank you! I'm working on the Settings page. However, I'm busy these days. It will take some time before available.

**Comment by oxdc** [comment]
Hi @mjmaurer ! Setting Tab is now available in v0.12.0. Thank you.
