### ISSUE TITLE
When simultaneously operating on Obsidian's native page and Vertical Tabs, there are some problems:

### ISSUE THREAD

**Issue by bakebakebakebake** [oxdc/obsidian-vertical-tabs#69]
If I click on a file in the file list while operating simultaneously, in Vertical Tabs, only the selected tab in the last group will change, and no other selections can be made. This can result in a poor user experience when working with multiple groups, so I hope this issue can be improved. 😘

>My feeling is that a default tab is selected for each group, so when clicking on a file in the file list, it is unclear which group to select. I hope this can be addressed specifically.

I have tested it, and it seems that it may not always be the last group. As for the specific rules, I am very confused, but overall, it seems there is an issue.

**Comment by oxdc** [comment]
Hi @bakebakebakebake ! What you described seems to be [this issue](https://github.com/oxdc/obsidian-vertical-tabs/issues/49#issue-2628554254). Could you please confirm if I am correct? Thank you. If possible, you can post some screenshots of what you desired and what you got.

**Comment by bakebakebakebake** [comment]
I noticed this issue as well, but it seems that some of the options in your video do not appear in my Obsidian. Is that version not yet released?

>For example, the option to always open in this group does not seem to be available in my version.If that option is available, then it seems like the problem would be resolved.

**Comment by oxdc** [comment]
No, it is not released. I am still working on it, but will be available soon. I provided several working-arounds in that issue. I'll close this issue right now. But feel free to comment or reopen it if necessary. Thank you.

**Comment by oxdc** [comment]
Duplicate: #49
