### ISSUE TITLE
Add option to place Vertical Tabs' sidebar at the top of the Files sidebar, similar to vscode

### ISSUE THREAD

**Issue by redoak** [oxdc/obsidian-vertical-tabs#70]
![image](https://github.com/user-attachments/assets/9b92abfb-d894-4372-8430-d28eb0dc26e2)
*Visual Studio Code's Explorer sidebar which lists all open tabs and the open folder (in this case EXAMPLE).*

I find how vscode displays open tabs and the open folder good for how I work. I would like to have an option in the plugin to, instead of having a separate sidebar for Vertical Tabs, add that content at the top of the Files sidebar.

- Being able to glance at the file structure in the sidebar without having to switching sidebar is helpful when I want to open a file I can't quite remember the name of.
- When I want to browse for a file, if the Vertical Tabs and Files sidebars were a single sidebar, it would save me the click to switch to the Files sidebar.

**Comment by oxdc** [comment]
Hi @redoak ! This functionality is already supported by Obsidian. You can simply drag the horizontal tab of File Browser to the bottom, or drag the Vertical Tabs to the bottom. You can make splits in sidebars, just as in the main areas. If you encounter any problems, please let me know. Thank you.
