### ISSUE TITLE
Clashes with the hover editor plugin

### ISSUE THREAD

**Issue by spiritualgeek** [oxdc/obsidian-vertical-tabs#75]
If you are working through notes and hover a link that just happens to be open in a tab somewhere, your plugin should not close the hover window

Thanks

**Comment by oxdc** [comment]
Hi @spiritualgeek ! Could you please include a screenshot or recording of expected behavior and actual behavior? Thank you!

**Comment by oxdc** [comment]
Hi @spiritualgeek ! I reproduced and fixed this bug. Will be available soon.
