### ISSUE TITLE
Mouse Focus Returns to Note Editor in IDE and Notebook Mode

### ISSUE THREAD

**Issue by kris-lu-dev** [oxdc/obsidian-vertical-tabs#77]
### Bug Description:

When using the plugin in **IDE** or **Notebook** Mode, attempting to interact with the **Left Sidebar** or **Right Sideba**r—such as searching, renaming files, or editing folder names—causes **the mouse focus to automatically jump back** to the original focus position in the note editor. This behavior prevents me from completing sidebar actions like searching or editing file/folder names.

Steps to Reproduce:
	1.	Switch to IDE or Notebook Mode.
	2.	Click on the Left Sidebar or Right Sidebar to search or edit a file/folder name.
	3.	Observe that the mouse focus jumps back to the note editor, interrupting the intended action.

### Expected Behavior:

The focus should remain in the sidebar when interacting with it, allowing actions such as search or file/folder name editing to proceed without interruption.

### Bug Demo

https://github.com/user-attachments/assets/425a2ecf-0379-4543-b12e-90442b858cd0

**Comment by kris-lu-dev** [comment]
Hi, 

I really like to use IDE mode to avoid opening the duplicate tab. However, this bug prevents me from doing search on the side bar. 

For now, I'm using the Omnisearch plugin instead.

I really hope this bug can be fixed soon.

**Comment by kris-lu-dev** [comment]
Hi,

I really like to use IDE mode to avoid opening the duplicate tab. However, this bug prevents me from doing search on the side bar.

For now, I'm using the Omnisearch plugin instead.

I really hope this bug can be fixed soon.

**Comment by oxdc** [comment]
Hi @kris-lu-dev ! Thank you for reporting this bug! I'll fix this ASAP.

**Comment by oxdc** [comment]
Hi @kris-lu-dev ! This should be fixed now. Please update and try out. Thank you!

**Comment by kris-lu-dev** [comment]
> Hi @kris-lu-dev ! This should be fixed now. Please update and try out. Thank you!

Thanks for great work! Now it works perfect!
