### ISSUE TITLE
Visual Glitch on tabs using obsidian 1.8.0

### ISSUE THREAD

**Issue by Azmoinal** [oxdc/obsidian-vertical-tabs#85]
### Bug Report Checklist

- [X] I have searched existing issues and this is not a duplicate
- [X] I have updated to the latest version of the plugin
- [X] I have disabled all other plugins and themes to ensure the issue is with Vertical Tabs
- [X] I have restarted Obsidian after disabling other plugins and themes, and the issue persists

### Environment

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] iPadOS

### Bug Description

The problem is related to _standard_ tabs: when zen mode is active, the only tab showed in the tab bar is not displayed properly.
See screenshot below as an example.

I tried disabling/enabling vertical tabs and the glitch appears only when VT is active. Probably it has been triggered by my update to latest catalyst Obsidian 1.8.0; indeed reinstalling previous 1.7.7 resolves the issue.

### Steps to Reproduce

To reproduce it.

1. Enable Vertical Tabs
2. Enable Zen Mode

Other Consideration:

1. Disabling "Show Active Tabs only" restores the right view (with Zen mode disabled)
2. With Background mode enabled right aspect is restored.

### Debug Information

SYSTEM INFO:
	Obsidian version: v1.8.0
	Installer version: v1.7.6
	Operating system: Windows 11 Pro 10.0.26100
	Login status: logged in
	Language: it
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 25
	Plugins enabled: 15
		1: Extract url content v0.12.1
		2: Local Backup v0.1.8
		3: Surfing v0.9.14
		4: Wikipedia Search v2.6.0
		5: Differential ZIP Backup v0.0.11
		6: File Color v1.1.0
		7: Tasks v7.14.0
		8: Highlightr v1.2.2
		9: Fast Text Color v1.1.2
		10: Style Settings v1.0.9
		11: Minimal Theme Settings v8.1.1
		12: Remember cursor position v1.0.9
		13: Typewriter Mode v1.0.0
		14: PDF++ v0.40.14
		15: Vertical Tabs v0.12.3

### Can you reproduce the bug in the "Sandbox vault"? Please skip this for mobile platforms by selecting "Not applicable".

Yes

### Screenshots

![Screenshot 2024-12-20 114440](https://github.com/user-attachments/assets/d5324289-8200-41fb-aec2-cd6d611991c1)
![Screenshot 2024-12-20 114509](https://github.com/user-attachments/assets/9502a5e6-7dfa-4b9f-aee8-4430b0fa78f3)

**Comment by oxdc** [comment]
Thank you for reporting this bug. I have fixed it in v0.12.4

**Comment by Azmoinal** [comment]
> Thank you for reporting this bug. I have fixed it in v0.12.4

Thanks a lot for the quick release!

**Comment by Azmoinal** [comment]
I'm sorry but, probably, I identified a remaining issue about this topic: in order to reproduce it, with obsidian 1.8 and latest Vertical Tabs, try the following the following steps:

1.  Disable Zen Mode
2. In Vertical Tabs settings enable "Show Active Tabs only".

You should see one tab for each pane, with the above mentioned visual issue. Instead, if zen mode is active, enabling/disabling "Show Active Tabs only" doesn't make any difference.

Just to be honest, It is not a configuration that I actively use; indeed I found it by mistake.
