### ISSUE TITLE
In older versions

### ISSUE THREAD

**Issue by Dopairym** [oxdc/obsidian-vertical-tabs#87]
### Enhancement Checklist

- [X] I have searched existing issues and this is not a duplicate
- [X] I am reporting a simple enhancement or improvement within Vertical Tabs, not requesting new features or addressing compatibility issues with other plugins
- [X] I understand that proposals for new features should be discussed in the ‘Discussions’ tab
- [X] I understand that compatibility issues with other plugins should be posted as a ‘Compatibility’ issue

### Enhancement Type

Usability

### Enhancement Description

In older versions of the plugin you could toggle the side bars In mobile and so you could change like the files and search from left side bar to right I liked that function if possible bring it back or give me like the version that had that function I think it was like 3 4 versions older

### Motivation

chaning sidebars mobile

**Comment by oxdc** [comment]
1. If you want to see sidebar tabs, please turn off "Hide sidebar tabs".
2. If you want the toggles available, just like those in previous versions, please turn on "Show more actions".

**IMPORTANT:** current version has some bugs, please try these features on your phone when the next release comes out.

<img width="1032" alt="SCR-20241226-sdve" src="https://github.com/user-attachments/assets/b480ba3f-1ac8-4318-8d5a-e32617e77322" />

**Comment by oxdc** [comment]
Hi @Dopairym ! The latest version now corrected some serious issues. You can try it out now. Thank you!
