### ISSUE TITLE
Local graph view will not open when Deduplicate tabs is enabled

### ISSUE THREAD

**Issue by ditmarvisser** [oxdc/obsidian-vertical-tabs#89]
### Bug Report Checklist

- [X] I have searched existing issues and this is not a duplicate
- [X] I have updated to the latest version of Vertical Tabs
- [X] I have disabled all other plugins and themes to ensure the issue is with Vertical Tabs
- [X] I have restarted Obsidian after disabling other plugins and themes, and the issue persists

### Environment (Optional)

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] iPadOS

### Bug Description

When the Deduplicate tabs option is active, the local graph view will not open. It will flash for a fraction of a second and close. When disabling the option it works as expected

### Steps to Reproduce

1. enable Deduplicate tabs 
2. open local graph view by way of command palette

### Debug Information

SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: Windows 11 Home 10.0.26100
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Border v1.10.9
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 37
	Plugins enabled: 36
		1: Style Settings v1.0.9
		2: Omnisearch v1.25.1
		3: Code Editor Shortcuts v1.14.0
		4: Templater v2.9.1
		5: Periodic Notes v0.0.17
		6: QuickAdd v1.11.5
		7: Lazy Plugin Loader v1.0.18
		8: Paste image rename v1.6.1
		9: Markdown Furigana v1.3.0
		10: Charts v3.9.0
		11: Execute Code v2.0.0
		12: Latex Suite v1.9.7
		13: Mermaid Tools v1.1.3
		14: Pandoc Reference List v2.0.25
		15: PlantUML v1.8.0
		16: Excalidraw v2.7.2
		17: Iconize v2.14.6
		18: Enhancing Export v1.10.9
		19: Commander v0.5.2
		20: Self-hosted LiveSync v0.24.6
		21: Calendarium v1.5.0
		22: Recent Files v1.7.3
		23: Settings Search v1.3.10
		24: Git v2.30.1
		25: Pomodoro Timer v1.2.3
		26: Advanced Slides v1.20.0
		27: Better Word Count v0.10.1
		28: Calendar v1.5.10
		29: Dataview v0.5.67
		30: Day Planner v0.27.0
		31: Tasks v7.14.0
		32: TikZJax v0.5.2
		33: Zotero Integration v3.2.1
		34: Smart Typography v1.0.18
		35: Vertical Tabs v0.12.4
		36: Linter v1.28.0

### Can you reproduce the bug in the "Sandbox vault"? Please skip this for mobile platforms by selecting "Not applicable".

Yes

**Comment by oxdc** [comment]
Hi @ditmarvisser ! Thank you for reporting this issue. The fix will be released soon.

**Comment by oxdc** [comment]
Hi @ditmarvisser ! Thank you, the new release is now available.
