### ISSUE TITLE
Some minor enhancements

### ISSUE THREAD

**Issue by Azona77** [oxdc/obsidian-vertical-tabs#9]
Finally a plugin that can replace the default tab bar! 

Here are a few minor enhancements:
- Closing tabs by middle button (maybe someone prefer double click?);
- A "new tab" button after existing tabs (like it in browsers). In the case of grouping, putting it in the last group should be fine;
- Adding a "collapse sidebar" button at the top right corner in zen mode:
  - The default collapse button only shows up at the top right tab in split view. It seems not possible to fix using css only? Maybe auto collapsing sidebar when entering zen mode should be good.
  - ![image](https://github.com/user-attachments/assets/74e6ad95-3be8-4528-8ca3-89d9f43b0db7)

**Comment by oxdc** [comment]
> Closing tabs by middle button (maybe someone prefer double click?);
> A "new tab" button after existing tabs (like it in browsers). In the case of grouping, putting it in the last group should be fine;

Thanks! These two features would be available soon! Stay tuned 🎉

> Adding a "collapse sidebar" button at the top right corner in zen mode.

Sorry, I didn't catch that. Could you please upload two screenshots to indicate the original and desired locations of the button, respectively? You may draw a tiny red box to mark the desired spot.

Zen Mode will be more configurable in the next major update. You would be able to choose which UI element should be hidden, including auto collapsing sidebars.

**Comment by oxdc** [comment]
Thanks for the detailed explanation. I have moved this to a new issue #10

**Comment by oxdc** [comment]
Hi! I have implemented all these features, including a bug fix for #10. Will be shipped in the next release.
