### ISSUE TITLE
Web view core plug-in interferes

### ISSUE THREAD

**Issue by DutchPete** [oxdc/obsidian-vertical-tabs#90]
### Bug Report Checklist

- [X] I have searched existing issues and this is not a duplicate
- [X] I have updated to the latest version of Vertical Tabs
- [X] I have disabled all other plugins and themes to ensure the issue is with Vertical Tabs
- [X] I have restarted Obsidian after disabling other plugins and themes, and the issue persists

### Environment (Optional)

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] iPadOS

### Bug Description

When I click on a URL in my note, the web page opens in Obsidian thanks to the Web View plug-in, but afterwards I need to disable and re-enable VT to make it work properly.

### Steps to Reproduce

1. Open Obsidian
2. Enable the Vertical Tabs plug-in.
3. Open 2 or 3 notes
4. Open a URL from an Obsidian note.
5. Close that web page.
6. The VT pane is empty, no open tabs are shown.
7. Disable then re-enable VT.
8. Open tabs are visible again.

### Debug Information

SYSTEM INFO:
	Obsidian version: v1.8.0
	Installer version: v1.6.5
	Operating system: #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) 6.1.0-28-amd64
	Login status: not logged in
	Language: en
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: ITS Theme v1.3.30
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 27
	Plugins enabled: 23
		1: Contextual Typography v2.2.5
		2: Copy Block Link v1.0.4
		3: Daily Notes Editor v0.1.8
		4: Hotkey Helper v0.3.20
		5: Link Keeper v0.1.2
		6: Outline++ v0.2.0
		7: Outliner v4.8.1
		8: Persistent Links v0.2.0
		9: Snippet Commands v0.0.2
		10: Style Settings v1.0.9
		11: Theme Design Utilities v0.22.1
		12: Smart Typography v1.0.18
		13: Hider v1.5.1
		14: Harper v0.12.0
		15: Enhanced Symbols Prettifier v1.4.1
		16: Replace All v1.0.5
		17: Number Headings v1.16.0
		18: Automatic Table Of Contents v1.5.0
		19: Better Markdown Links v2.10.2
		20: BRAT v1.0.6
		21: Callout Toggles v1.1.0
		22: Strange New Worlds v2.3.2
		23: Vertical Tabs v0.12.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Can you reproduce the bug in the "Sandbox vault"? Please skip this for mobile platforms by selecting "Not applicable".

Yes

### Additional Information (Optional)

I have VT set such that tabs are only visible in the side pane – can't remember how I did that.

In the sandbox, the tabs were show both vertically and horizontally. The vertical tabs show the same behavior as described above.

The horizontal ones show something different. The note with the URL is replaced by the webpage. When the web page is closed, the note with the URL remains closed, soyou have to open it with `CTRL+O`.

**Comment by oxdc** [comment]
Hi @DutchPete ! This bug has been fixed and the next version will be publicly available soon.

> I have VT set such that tabs are only visible in the side pane – can't remember how I did that.

If I am correct, you should have enabled "Show active tabs only" in the settings. You can change that if you like.

**Comment by oxdc** [comment]
Hi @DutchPete ! The updated version is now available.

**Comment by DutchPete** [comment]
Perfect! Many thanks, Patrizio.
